services:
  test-app-5:
    image: ghcr.io/corentinclero/test-app-5-front:latest
    container_name: test-app-5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test-app-5.rule=Host(`test-app-5.sleipnir.ovh`)"
      - "traefik.http.routers.test-app-5.entrypoints=websecure"
      - "traefik.http.routers.test-app-5.tls.certresolver=letsencrypt"
      - "traefik.http.routers.test-app-5-http.rule=Host(`test-app-5.sleipnir.ovh`)"
      - "traefik.http.routers.test-app-5-http.entrypoints=web"
      - "traefik.http.routers.test-app-5-http.middlewares=test-app-5-redirect-to-https"
      - "traefik.http.middlewares.test-app-5-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.test-app-5.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  default:
    external: true
    name: traefik_default