services:
  test-app-5-api:
    image: ghcr.io/corentinclero/test-app-5-api:latest
    container_name: test-app-5-api
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_ACCESS_EXPIRES_IN=${JWT_ACCESS_EXPIRES_IN:-15m}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-7d}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test-app-5-api.rule=Host(`test-app-5-api.sleipnir.ovh`)"
      - "traefik.http.routers.test-app-5-api.entrypoints=websecure"
      - "traefik.http.routers.test-app-5-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.test-app-5-api-http.rule=Host(`test-app-5-api.sleipnir.ovh`)"
      - "traefik.http.routers.test-app-5-api-http.entrypoints=web"
      - "traefik.http.routers.test-app-5-api-http.middlewares=test-app-5-api-redirect-to-https"
      - "traefik.http.middlewares.test-app-5-api-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.test-app-5-api.loadbalancer.server.port=3000"
    restart: unless-stopped

networks:
  default:
    external: true
    name: traefik_default